name: deaddomain
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'dead'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          close-reason: not_planned
          comment: Thanks for the support, but the listed domain(s) do not exist (status NXDOMAIN). Dead domains are not added to my lists.
