name: ignored
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'ignored'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          close-reason: not_planned
          comment: The requested details in the issue template were not provided. The information is either completely missing or insufficient. Issues lacking required details are not processed.
